import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, Bot, Check, Database, Inbox, MessageCircle, PenLine, Search, Send, Sparkles, TrendingUp, UploadCloud, UserPlus, Users, Zap } from 'lucide-react'
import { categories, collaborationInvites, followerFilters, influencers, roles, seededMessages } from './data'
import './style.css'

const formatFollowers = (value) => value >= 10000 ? `${(value / 10000).toFixed(value >= 1000000 ? 0 : 1)}万` : value.toLocaleString('zh-CN')
const formatCurrency = (value) => `¥${value.toLocaleString('zh-CN')}`

function Navbar({ onHome, role, setRole }) {
  return (
    <header className="sticky top-0 z-40 border-b border-white/60 bg-white/85 backdrop-blur-xl">
      <nav className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8">
        <button onClick={onHome} className="flex items-center gap-3 text-left">
          <span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-pink-500 to-violet-600 text-white shadow-glow"><Sparkles size={22} /></span>
          <span><strong className="block text-lg text-slate-950">人人网红平台</strong><small className="text-slate-500">Real Creator Marketplace</small></span>
        </button>
        <div className="flex flex-wrap items-center gap-2 text-sm font-bold">
          {roles.map((item) => <button key={item.id} onClick={() => setRole(item.id)} className={`rounded-full px-4 py-2 transition ${role === item.id ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-600 hover:bg-pink-50 hover:text-pink-600'}`}>{item.label}</button>)}
        </div>
      </nav>
    </header>
  )
}

function FollowButton({ isFollowing, onToggle, compact = false }) {
  return <button onClick={onToggle} className={`inline-flex items-center justify-center gap-2 rounded-2xl font-bold transition ${compact ? 'px-3 py-2 text-xs' : 'px-4 py-3 text-sm'} ${isFollowing ? 'bg-pink-50 text-pink-600 ring-1 ring-pink-100 hover:bg-pink-100' : 'bg-slate-950 text-white hover:bg-gradient-to-r hover:from-pink-500 hover:to-violet-600'}`}>{isFollowing ? <Check size={16} /> : <UserPlus size={16} />}{isFollowing ? '已关注' : '关注'}</button>
}

function InfluencerCard({ influencer, onSelect, isFollowing, onToggleFollow }) {
  return (
    <article className="group overflow-hidden rounded-3xl border border-white/70 bg-white/85 p-5 shadow-xl shadow-slate-200/60 transition hover:-translate-y-1 hover:shadow-glow">
      <div className="flex items-start gap-4">
        <img className="h-20 w-20 rounded-3xl object-cover ring-4 ring-pink-100" src={influencer.avatar} alt={`${influencer.name} 头像`} />
        <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="truncate text-xl font-bold text-slate-950">{influencer.name}</h3><span className="rounded-full bg-pink-50 px-3 py-1 text-xs font-semibold text-pink-600">{influencer.category}</span></div><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-slate-700"><Users size={16} />{formatFollowers(influencer.followers)} 粉丝</p></div>
      </div>
      <p className="mt-5 min-h-16 text-sm leading-7 text-slate-600">{influencer.bio}</p>
      <div className="mt-4 flex flex-wrap gap-2">{influencer.tags.map((tag) => <span key={tag} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">#{tag}</span>)}</div>
      <div className="mt-5 grid grid-cols-3 gap-3 rounded-2xl bg-slate-50 p-3 text-sm"><DataMini label="报价" value={formatCurrency(influencer.price)} /><DataMini label="互动" value={influencer.stats.engagement} /><DataMini label="档期" value={influencer.availability} /></div>
      <div className="mt-5 grid grid-cols-[1fr_auto] gap-3"><button onClick={() => onSelect(influencer)} className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition group-hover:bg-gradient-to-r group-hover:from-pink-500 group-hover:to-violet-600">查看主页 / 报价</button><FollowButton isFollowing={isFollowing} onToggle={onToggleFollow} compact /></div>
    </article>
  )
}

function BrandDiscovery({ query, setQuery, category, setCategory, followerMin, setFollowerMin, requirement, setRequirement, matches }) {
  return <section id="discover" className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8"><div className="rounded-3xl border border-white/70 bg-white/80 p-5 shadow-xl shadow-slate-200/70"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto]"><label className="flex items-center gap-3 rounded-2xl bg-slate-100 px-4 py-3 text-slate-500"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索昵称、简介、标签或领域" className="w-full bg-transparent text-slate-900 outline-none" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-2xl bg-slate-100 px-4 py-3 font-bold text-slate-700 outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={followerMin} onChange={(event) => setFollowerMin(Number(event.target.value))} className="rounded-2xl bg-slate-100 px-4 py-3 font-bold text-slate-700 outline-none">{followerFilters.map((item) => <option key={item.label} value={item.min}>{item.label}</option>)}</select></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_360px]"><textarea value={requirement} onChange={(event) => setRequirement(event.target.value)} className="min-h-24 rounded-2xl bg-slate-100 px-4 py-3 text-slate-900 outline-none focus:ring-2 focus:ring-pink-200" placeholder="输入品牌需求，AI 会按领域、粉丝量、标签和预算推荐达人。例如：美妆新品，预算 7 万，想要测评和直播种草" /><div className="rounded-2xl bg-gradient-to-br from-slate-950 to-violet-800 p-4 text-white"><p className="flex items-center gap-2 text-sm font-bold text-pink-200"><Bot size={18} />AI 匹配推荐</p>{matches.slice(0, 2).map((item) => <p key={item.id} className="mt-3 text-sm"><strong>{item.name}</strong> · 匹配度 {item.score}% · {item.reason}</p>)}</div></div></div></section>
}

function HomePage({ onSelect, followingIds, onToggleFollow, role }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('全部')
  const [followerMin, setFollowerMin] = useState(0)
  const [requirement, setRequirement] = useState('美妆新品，预算 7 万，希望测评和直播种草')
  const filtered = useMemo(() => influencers.filter((item) => [item.name, item.bio, item.category, item.tags.join(' ')].join(' ').toLowerCase().includes(query.trim().toLowerCase()) && (category === '全部' || item.category === category) && item.followers >= followerMin), [query, category, followerMin])
  const matches = useMemo(() => influencers.map((item) => ({ ...item, score: Math.min(98, 62 + (requirement.includes(item.category) ? 18 : 0) + item.tags.filter((tag) => requirement.includes(tag)).length * 8 + (item.price <= 70000 ? 8 : 0)), reason: `${item.category}领域 / ${formatFollowers(item.followers)}粉丝 / 报价${formatCurrency(item.price)}` })).sort((a, b) => b.score - a.score), [requirement])
  return <main><section className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8 lg:py-20"><div><span className="inline-flex rounded-full bg-white px-4 py-2 text-sm font-semibold text-pink-600 shadow">注册登录 · 达人后台 · 品牌寻源 · 实时聊天</span><h1 className="mt-6 text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">升级为可运营的真实网红合作平台</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">支持品牌、网红、普通用户三种账号视角；品牌可按粉丝量和领域筛选、查看报价并使用 AI 匹配；网红可维护简介、上传作品、查看合作邀请。</p></div><PlatformStatus /></section>{role === 'brand' && <BrandDiscovery query={query} setQuery={setQuery} category={category} setCategory={setCategory} followerMin={followerMin} setFollowerMin={setFollowerMin} requirement={requirement} setRequirement={setRequirement} matches={matches} />}{role === 'influencer' && <InfluencerDashboard />}{role === 'user' && <UserLanding /> }<section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><div className="mt-2 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <InfluencerCard key={item.id} influencer={item} onSelect={onSelect} isFollowing={followingIds.includes(item.id)} onToggleFollow={() => onToggleFollow(item.id)} />)}</div></section></main>
}

function PlatformStatus() { return <div className="rounded-[2rem] bg-gradient-to-br from-pink-500 to-violet-700 p-8 text-white shadow-glow"><p className="text-sm uppercase tracking-[0.3em] text-white/70">Phase 2 Infrastructure</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Status icon={Database} title="数据库接入" text="用户、作品、报价、邀请与消息模型" /><Status icon={Zap} title="实时消息" text="模拟 WebSocket 在线收发与自动回复" /><Status icon={Bot} title="AI 匹配" text="按需求文本计算达人匹配度" /><Status icon={Users} title="三类账号" text="品牌 / 网红 / 普通用户登录入口" /></div></div> }
function Status({ icon: Icon, title, text }) { return <div className="rounded-2xl bg-white/15 p-4"><Icon /><p className="mt-3 font-bold">{title}</p><p className="mt-1 text-sm text-white/75">{text}</p></div> }
function DataMini({ label, value }) { return <div><p className="text-xs text-slate-400">{label}</p><strong className="mt-1 block truncate text-slate-800">{value}</strong></div> }
function Data({ label, value }) { return <div className="rounded-2xl bg-white p-4"><p className="text-sm text-slate-500">{label}</p><strong className="mt-1 block text-2xl text-slate-950">{value}</strong></div> }

function InfluencerDashboard() { const [bio, setBio] = useState(influencers[0].intro); const [works, setWorks] = useState(influencers[0].works); const [workTitle, setWorkTitle] = useState(''); const addWork = (event) => { event.preventDefault(); if (!workTitle.trim()) return; setWorks((current) => [workTitle.trim(), ...current]); setWorkTitle('') }; return <section className="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-[1fr_0.9fr]"><div className="rounded-3xl bg-white p-6 shadow-xl shadow-slate-200/70"><h2 className="flex items-center gap-2 text-2xl font-black"><PenLine className="text-pink-500" />网红后台</h2><label className="mt-5 block text-sm font-bold text-slate-500">修改简介</label><textarea value={bio} onChange={(event) => setBio(event.target.value)} className="mt-2 min-h-36 w-full rounded-2xl bg-slate-100 p-4 outline-none focus:ring-2 focus:ring-pink-200" /><form onSubmit={addWork} className="mt-5 flex gap-3"><input value={workTitle} onChange={(event) => setWorkTitle(event.target.value)} placeholder="上传新作品标题" className="min-w-0 flex-1 rounded-2xl bg-slate-100 px-4 py-3 outline-none" /><button className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 font-bold text-white"><UploadCloud size={18} />上传</button></form><div className="mt-4 flex flex-wrap gap-2">{works.map((work) => <span key={work} className="rounded-full bg-pink-50 px-3 py-1 text-sm font-bold text-pink-600">{work}</span>)}</div></div><div className="rounded-3xl bg-white p-6 shadow-xl shadow-slate-200/70"><h2 className="flex items-center gap-2 text-2xl font-black"><Inbox className="text-pink-500" />合作邀请</h2><div className="mt-5 space-y-3">{collaborationInvites.map((invite) => <div key={invite.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex justify-between gap-3"><strong>{invite.brand}</strong><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">{invite.status}</span></div><p className="mt-2 text-slate-600">{invite.campaign}</p><p className="mt-2 text-sm font-bold text-pink-600">预算 {invite.budget} · 截止 {invite.due}</p></div>)}</div></div></div></section> }
function UserLanding() { return <section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 lg:px-8"><div className="rounded-3xl bg-white p-6 shadow-xl shadow-slate-200/70"><h2 className="text-2xl font-black">普通用户视角</h2><p className="mt-3 text-slate-600">普通用户可以浏览达人主页、关注喜欢的创作者，并通过作品内容了解真实风格与互动表现。</p></div></section> }

function ChatBox({ influencer }) {
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState(seededMessages)
  const handleSend = (event) => { event.preventDefault(); const trimmed = message.trim(); if (!trimmed) return; setMessages((current) => [...current, { id: Date.now(), from: '我', text: trimmed, time: '刚刚' }, { id: Date.now() + 1, from: influencer.name, text: '已收到需求，我会结合报价、档期和内容形式给出合作方案。', time: '实时' }]); setMessage('') }
  return <aside className="rounded-3xl border border-pink-100 bg-white p-5 shadow-xl shadow-slate-200/70"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-pink-50 text-pink-600"><MessageCircle size={20} /></span><div><h2 className="font-black text-slate-950">实时私信</h2><p className="text-sm text-slate-500">模拟数据库消息流与在线自动回复</p></div></div><div className="mt-4 max-h-72 space-y-3 overflow-y-auto pr-1">{messages.map((item) => <div key={item.id} className={`rounded-2xl p-3 text-sm leading-6 ${item.from === '我' ? 'ml-8 bg-gradient-to-r from-pink-500 to-violet-600 text-white' : 'mr-8 bg-slate-100 text-slate-600'}`}><strong className="mb-1 block text-xs opacity-80">{item.from} · {item.time}</strong>{item.text}</div>)}</div><form onSubmit={handleSend} className="mt-4 flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="输入预算、档期或内容需求..." className="min-w-0 flex-1 rounded-2xl bg-slate-100 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-pink-200" /><button className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white transition hover:bg-pink-500" aria-label="发送消息"><Send size={18} /></button></form></aside>
}

function ProfilePage({ influencer, onBack, isFollowing, onToggleFollow }) { return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><button onClick={onBack} className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 font-semibold text-slate-700 shadow hover:text-pink-600"><ArrowLeft size={18} />返回列表</button><section className="overflow-hidden rounded-[2rem] bg-white shadow-2xl shadow-slate-200"><div className="h-36 bg-gradient-to-r from-pink-400 via-fuchsia-500 to-violet-700" /><div className="px-6 pb-8 sm:px-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><img className="-mt-16 h-32 w-32 rounded-[2rem] border-4 border-white object-cover shadow-xl" src={influencer.avatar} alt={`${influencer.name} 头像`} /><FollowButton isFollowing={isFollowing} onToggle={onToggleFollow} /></div><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_340px]"><div><span className="rounded-full bg-pink-50 px-3 py-1 text-sm font-bold text-pink-600">{influencer.category}</span><h1 className="mt-4 text-4xl font-black text-slate-950">{influencer.name}</h1><p className="mt-5 text-lg leading-9 text-slate-600">{influencer.intro}</p></div><div className="grid gap-4 rounded-3xl bg-slate-50 p-5"><Data label="粉丝数量" value={formatFollowers(influencer.followers)} /><Data label="合作报价" value={formatCurrency(influencer.price)} /><Data label="互动率" value={influencer.stats.engagement} /><Data label="粉丝增长" value={influencer.growth} /></div></div></div></section><section className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div id="works"><h2 className="text-2xl font-black text-slate-950">代表作品</h2><div className="mt-5 grid gap-5 md:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">{influencer.works.map((work, index) => <div key={work} className="rounded-3xl bg-white p-6 shadow-xl shadow-slate-200/70"><span className="text-sm font-bold text-pink-500">作品 0{index + 1}</span><h3 className="mt-4 text-xl font-black text-slate-900">{work}</h3><p className="mt-3 text-sm leading-6 text-slate-500">短视频、图文与直播片段组合展示，适合品牌快速评估内容风格。</p></div>)}</div></div><ChatBox influencer={influencer} /></section></main> }

function App() { const [selected, setSelected] = useState(null); const [followingIds, setFollowingIds] = useState([]); const [role, setRole] = useState('brand'); const toggleFollow = (id) => setFollowingIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); return <><Navbar onHome={() => setSelected(null)} role={role} setRole={setRole} />{selected ? <ProfilePage influencer={selected} onBack={() => setSelected(null)} isFollowing={followingIds.includes(selected.id)} onToggleFollow={() => toggleFollow(selected.id)} /> : <HomePage onSelect={setSelected} followingIds={followingIds} onToggleFollow={toggleFollow} role={role} />}<footer className="px-4 py-10 text-center text-sm text-slate-500">© 2026 人人网红平台 · 连接品牌与优质创作者 · 数据库 / 实时消息 / AI 匹配能力原型</footer></> }

createRoot(document.getElementById('root')).render(<App />)
